apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tst-layers-app-pre-prod

patchesStrategicMerge:
- replicas_patch.yaml
    
resources:
- namespace.yaml

bases:
- ../../base





